// Shared StyleSheet for the login/checkout sheet steps.
//
// Extracted from LoginBottomSheet.tsx, where 360 lines of styles sat below six
// step components and the orchestrator in a single 1108-line file.

import { StyleSheet } from 'react-native';

export const s = StyleSheet.create({
  stepContainer: {
    paddingHorizontal: 20,
    paddingBottom: 28,
    paddingTop: 4,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  badge: {
    backgroundColor: '#f0fdf4',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
  },
  badgeText: {
    color: '#15803d',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1,
  },
  iconBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    marginTop: 12,
    fontSize: 22,
    fontWeight: '900',
    color: '#0f172a',
    letterSpacing: -0.3,
    lineHeight: 28,
  },
  subtitle: {
    marginTop: 4,
    fontSize: 12.5,
    color: '#64748b',
    lineHeight: 18,
  },
  phoneBold: {
    fontWeight: '800',
    color: '#1e293b',
  },
  simChip: {
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'flex-start',
    backgroundColor: '#f0fdf4',
    borderWidth: 1,
    borderColor: '#bbf7d0',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  simChipText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#15803d',
  },
  phoneRow: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#e2e8f0',
    backgroundColor: '#fff',
    height: 52,
  },
  phoneRowValid: {
    borderColor: '#16a34a',
    backgroundColor: '#f0fdf4',
  },
  prefix: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    borderRightWidth: 1,
    borderRightColor: '#e2e8f0',
    height: '100%',
  },
  flag: { fontSize: 18 },
  countryCode: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0f172a',
  },
  phoneInput: {
    flex: 1,
    paddingHorizontal: 12,
    fontSize: 16,
    fontWeight: '700',
    color: '#0f172a',
  },
  validCheck: {
    paddingRight: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#16a34a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  trustRow: {
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  trustItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  trustLabel: {
    fontSize: 10.5,
    fontWeight: '600',
    color: '#94a3b8',
    letterSpacing: 0.2,
  },
  cta: {
    marginTop: 20,
    height: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ctaActive: {
    backgroundColor: '#16a34a',
    shadowColor: '#16a34a',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 20,
    elevation: 12,
  },
  ctaDisabled: {
    backgroundColor: '#f1f5f9',
  },
  ctaText: {
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  ctaTextActive: { color: '#fff' },
  ctaTextDisabled: { color: '#94a3b8' },
  legal: {
    marginTop: 12,
    textAlign: 'center',
    fontSize: 10.5,
    lineHeight: 16,
    color: '#64748b',
    paddingHorizontal: 12,
  },
  legalLink: {
    fontWeight: '700',
    color: '#334155',
    textDecorationLine: 'underline',
  },
  // OTP step
  otpSubtitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  smsHint: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    alignSelf: 'flex-start',
  },
  smsDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#22c55e',
    alignItems: 'center',
    justifyContent: 'center',
  },
  smsDotInner: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#16a34a',
  },
  smsHintText: {
    fontSize: 10.5,
    fontWeight: '700',
    color: '#475569',
    letterSpacing: 0.2,
  },
  otpRow: {
    marginTop: 20,
    flexDirection: 'row',
    gap: 8,
  },
  otpBox: {
    flex: 1,
    height: 56,
    borderRadius: 12,
    borderWidth: 2,
    fontSize: 22,
    fontWeight: '900',
    color: '#0f172a',
  },
  otpBoxEmpty: {
    borderColor: '#e2e8f0',
    backgroundColor: '#fff',
  },
  otpBoxActive: {
    borderColor: '#cbd5e1',
    backgroundColor: '#fff',
  },
  otpBoxFilled: {
    borderColor: '#16a34a',
    backgroundColor: '#f0fdf4',
  },
  otpBoxError: {
    borderColor: '#f43f5e',
    backgroundColor: '#fff1f2',
  },
  errorText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#e11d48',
  },
  verifyingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  verifyingText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748b',
  },
  resendRow: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  resendLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  resendTimer: {
    fontSize: 11.5,
    fontWeight: '600',
    color: '#64748b',
  },
  resendBtn: {
    fontSize: 12,
    fontWeight: '800',
    color: '#15803d',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  resendBtnDisabled: {
    color: '#cbd5e1',
  },
  // Placing / success
  centeredStep: {
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 40,
    alignItems: 'center',
  },
  spinnerWrap: {
    width: 80,
    height: 80,
    alignItems: 'center',
    justifyContent: 'center',
  },
  spinnerBg: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 40,
    backgroundColor: '#f0fdf4',
  },
  spinnerRing: {
    position: 'absolute',
    top: 4,
    left: 4,
    right: 4,
    bottom: 4,
    borderRadius: 36,
    borderWidth: 4,
    borderColor: '#16a34a',
    borderRightColor: 'transparent',
  },
  pulseRing: {
    position: 'absolute',
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 2,
    borderColor: '#bbf7d0',
  },
  checkCircleBg: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#16a34a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorCircleBg: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#fef2f2',
    borderWidth: 1.5,
    borderColor: '#fecaca',
    alignItems: 'center',
    justifyContent: 'center',
  },
  centeredTitle: {
    marginTop: 20,
    fontSize: 18,
    fontWeight: '900',
    color: '#0f172a',
  },
  centeredSubtitle: {
    marginTop: 4,
    fontSize: 12.5,
    color: '#64748b',
    lineHeight: 18,
  },
  smsConfirm: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  smsConfirmText: {
    fontSize: 10.5,
    fontWeight: '600',
    color: '#94a3b8',
  },
});
